[project]
name = "idp2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "neutronleak", email = "joni.hyttinen@uef.fi" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
idp2025 = "idp2025:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
